package pages;
/**
 *
 * @author Reinaldo Taslim
 */
import java.awt.Color;
import javax.swing.JOptionPane;
import model.User;

public class AdminPage extends javax.swing.JFrame {
    private User user;
    
    public AdminPage(User user) {
        super("Admin Page");
        this.user = user;
        setSize(1280, 720);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        CustomerPanel = new javax.swing.JPanel();
        CustomerLogo = new javax.swing.JLabel();
        CustomerLabel = new javax.swing.JLabel();
        ProductPanel = new javax.swing.JPanel();
        ProductLogo = new javax.swing.JLabel();
        ProductLabel = new javax.swing.JLabel();
        OrderPanel = new javax.swing.JPanel();
        OrderLogo = new javax.swing.JLabel();
        OrderLabel = new javax.swing.JLabel();
        MyAccountPanel = new javax.swing.JPanel();
        MyAccountLabel = new javax.swing.JLabel();
        LogoutPanel = new javax.swing.JPanel();
        LogoutLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(153, 153, 153));

        CustomerPanel.setBackground(new java.awt.Color(204, 204, 204));
        CustomerPanel.setPreferredSize(new java.awt.Dimension(266, 278));
        CustomerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CustomerPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CustomerPanelMouseExited(evt);
            }
        });

        CustomerLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/Customer.png"))); // NOI18N

        CustomerLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        CustomerLabel.setText("Customer");

        javax.swing.GroupLayout CustomerPanelLayout = new javax.swing.GroupLayout(CustomerPanel);
        CustomerPanel.setLayout(CustomerPanelLayout);
        CustomerPanelLayout.setHorizontalGroup(
            CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(CustomerLogo)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerPanelLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(CustomerLabel)
                .addGap(78, 78, 78))
        );
        CustomerPanelLayout.setVerticalGroup(
            CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPanelLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(CustomerLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomerLabel)
                .addGap(34, 34, 34))
        );

        ProductPanel.setBackground(new java.awt.Color(204, 204, 204));
        ProductPanel.setPreferredSize(new java.awt.Dimension(266, 278));
        ProductPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProductPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductPanelMouseExited(evt);
            }
        });

        ProductLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/Product.png"))); // NOI18N

        ProductLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        ProductLabel.setText("Product");

        javax.swing.GroupLayout ProductPanelLayout = new javax.swing.GroupLayout(ProductPanel);
        ProductPanel.setLayout(ProductPanelLayout);
        ProductPanelLayout.setHorizontalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(ProductLogo))
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(ProductLabel)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        ProductPanelLayout.setVerticalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProductLogo)
                .addGap(18, 18, 18)
                .addComponent(ProductLabel)
                .addGap(34, 34, 34))
        );

        OrderPanel.setBackground(new java.awt.Color(204, 204, 204));
        OrderPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OrderPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OrderPanelMouseExited(evt);
            }
        });

        OrderLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/Order.png"))); // NOI18N

        OrderLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        OrderLabel.setText("Order");

        javax.swing.GroupLayout OrderPanelLayout = new javax.swing.GroupLayout(OrderPanel);
        OrderPanel.setLayout(OrderPanelLayout);
        OrderPanelLayout.setHorizontalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(OrderLabel))
                    .addGroup(OrderPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(OrderLogo)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        OrderPanelLayout.setVerticalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(OrderLogo)
                .addGap(18, 18, 18)
                .addComponent(OrderLabel)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        MyAccountPanel.setBackground(new java.awt.Color(204, 204, 204));
        MyAccountPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyAccountPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyAccountPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyAccountPanelMouseExited(evt);
            }
        });

        MyAccountLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        MyAccountLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/MyAccount.png"))); // NOI18N
        MyAccountLabel.setText("My Account");

        javax.swing.GroupLayout MyAccountPanelLayout = new javax.swing.GroupLayout(MyAccountPanel);
        MyAccountPanel.setLayout(MyAccountPanelLayout);
        MyAccountPanelLayout.setHorizontalGroup(
            MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyAccountPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(MyAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        MyAccountPanelLayout.setVerticalGroup(
            MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyAccountPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(MyAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        LogoutPanel.setBackground(new java.awt.Color(204, 204, 204));
        LogoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseExited(evt);
            }
        });

        LogoutLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/Logout.png"))); // NOI18N

        javax.swing.GroupLayout LogoutPanelLayout = new javax.swing.GroupLayout(LogoutPanel);
        LogoutPanel.setLayout(LogoutPanelLayout);
        LogoutPanelLayout.setHorizontalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutLogo)
                .addContainerGap())
        );
        LogoutPanelLayout.setVerticalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutLogo)
                .addContainerGap())
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(CustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(ProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(OrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MyAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MyAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProductPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OrderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustomerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MyAccountPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccountPanelMouseEntered
        MyAccountPanel.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_MyAccountPanelMouseEntered

    private void MyAccountPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccountPanelMouseExited
        MyAccountPanel.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_MyAccountPanelMouseExited

    private void MyAccountPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccountPanelMouseClicked
        this.dispose();
        new MyAccountPage(user).setVisible(true);
    }//GEN-LAST:event_MyAccountPanelMouseClicked

    private void LogoutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseEntered
        LogoutPanel.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_LogoutPanelMouseEntered

    private void LogoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseExited
        LogoutPanel.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_LogoutPanelMouseExited

    private void LogoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseClicked
        String[] options =  {"Yes", "No"};
        int choice = JOptionPane.showOptionDialog(null, "Are you sure you want to logout?",
                "Logout",
                JOptionPane.DEFAULT_OPTION, JOptionPane.YES_NO_OPTION, null, options, options[0]);
        if (choice == 0){
            this.dispose();
            new LoginPage().setVisible(true);
        }
    }//GEN-LAST:event_LogoutPanelMouseClicked

    private void CustomerPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerPanelMouseEntered
        CustomerPanel.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_CustomerPanelMouseEntered

    private void CustomerPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerPanelMouseExited
        CustomerPanel.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_CustomerPanelMouseExited

    private void CustomerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerPanelMouseClicked

    private void ProductPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductPanelMouseEntered
        ProductPanel.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_ProductPanelMouseEntered

    private void ProductPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductPanelMouseExited
        ProductPanel.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_ProductPanelMouseExited

    private void ProductPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductPanelMouseClicked

    private void OrderPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderPanelMouseEntered
        OrderPanel.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_OrderPanelMouseEntered

    private void OrderPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderPanelMouseExited
        OrderPanel.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_OrderPanelMouseExited

    private void OrderPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderPanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel CustomerLabel;
    private javax.swing.JLabel CustomerLogo;
    private javax.swing.JPanel CustomerPanel;
    private javax.swing.JLabel LogoutLogo;
    private javax.swing.JPanel LogoutPanel;
    private javax.swing.JLabel MyAccountLabel;
    private javax.swing.JPanel MyAccountPanel;
    private javax.swing.JLabel OrderLabel;
    private javax.swing.JLabel OrderLogo;
    private javax.swing.JPanel OrderPanel;
    private javax.swing.JLabel ProductLabel;
    private javax.swing.JLabel ProductLogo;
    private javax.swing.JPanel ProductPanel;
    // End of variables declaration//GEN-END:variables
}
